### ISSUE TITLE
Naming of middleware

### ISSUE THREAD

**Issue by alloy** [prismagraphql/graphql-middleware#11]
Before publishing our timeout middleware to npm, I figured I’d ask if you had a specific naming scheme in mind for middleware? I settled on `graphqlTimeoutMiddleware` for now: https://github.com/artsy/metaphysics/pull/1068

Thanks for this library btw!

**Comment by maticzav** [comment]
@alloy this is great! I love to hear that you enjoy using the library. There's no official convention, but I settled in Sentry plugin and Forwarding tool with `graphql-middleware-nameoflib`. 

I think we should create a website or at least a collection of the available plugins to make them easier to discover. Or, we could add them to README! What do you think?

**Comment by alloy** [comment]
I kinda like suggesting the convention in your README through means of adding a list of them all using the same pattern 👍
