### ISSUE TITLE
Add the ability to wrap only non-default resolvers

### ISSUE THREAD

**Issue by mdlavin** [prismagraphql/graphql-middleware#12]
I have found `graphql-middleware` to be very helpful when building https://github.com/lifeomic/graphql-resolvers-xray-tracing . Thank you for sharing it.

In that same project, I'd like to wrap only non-default resolvers and I thought others might want that same behavior. If you would accept it, I'd be happy to create a PR that adds a an option to the `applyMiddleware` function. Should I work on a PR that adds that feature?

**Comment by maticzav** [comment]
@mdlavin PR sounds great!
