### ISSUE TITLE
how to get passport's Auth info in this middleware

### ISSUE THREAD

**Issue by geminiyellow** [prismagraphql/graphql-middleware#8]
hi all, i use express + passport-oauth2 in my web.
and i want to use graphql to wrap exist restapi, with permission check.

i follow the examples/permissions , but in this line

https://github.com/prismagraphql/graphql-middleware/blob/6889d229181e49b4e8711d22a960900b103c2632/examples/permissions/index.js#L40

the `context.request.isAuthenticated()` alway false, 
and i debug into the code, it looks like the `this` have nothing about auth info.

anybody can tell me how to use this library whit passport ?

**Comment by maticzav** [comment]
Hey @geminiyellow 👋 Could you reopen this issue in https://github.com/maticzav/graphql-shield ? 

I think thsi might be well solved there!

**Comment by maticzav** [comment]
I am closing this issue in favour of the referenced issue in GraphQL Shield.
